# Generated by Django 4.2.2 on 2023-07-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_investmentsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.currency'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.investmentplan'),
        ),
    ]
