# Generated by Django 4.2.2 on 2023-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='daily_profit_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
