# Generated by Django 4.2.2 on 2023-07-27 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0005_alter_investmentplan_daily_profit_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentsinfo',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='investmentsinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profittransaction',
            name='investment',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='InvestmentPlan',
        ),
        migrations.DeleteModel(
            name='InvestmentsInfo',
        ),
    ]
