# Generated by Django 4.2.2 on 2023-07-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0007_userprofile_cryptowallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
