# Generated by Django 4.2.2 on 2023-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0011_dayprofit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptowalletaddress',
            name='currency',
        ),
        migrations.AddField(
            model_name='cryptowalletaddress',
            name='currency',
            field=models.ManyToManyField(to='dashboard.currency'),
        ),
    ]
