# Generated by Django 4.2.2 on 2023-07-31 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0012_remove_cryptowalletaddress_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptowalletaddress',
            name='currency',
        ),
        migrations.AddField(
            model_name='cryptowalletaddress',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.currency'),
            preserve_default=False,
        ),
    ]
