# Generated by Django 4.2.2 on 2023-07-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0013_remove_cryptowalletaddress_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowalletaddress',
            name='network',
            field=models.CharField(
                choices=[('BSC', 'BNB Smart Chain (BEP20)'), ('ETH', 'Ethereum (ERC20)'), ('TRX', 'Tron (TRC20)')],
                default=1, max_length=4),
            preserve_default=False,
        ),
    ]
