# Generated by Django 4.2.2 on 2023-07-31 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_cryptowalletaddress_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=5)),
                ('coin_image', models.ImageField(blank=True, null=True, upload_to='coin_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='cryptowalletaddress',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='profitwallet',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='walletreplenishmentrequest',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='walletwithdrawalrequest',
            name='currency',
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cryptowalletaddress',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.coin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.coin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitwallet',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.coin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.coin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.coin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletreplenishmentrequest',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.coin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletwithdrawalrequest',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.coin'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'coin')},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
