# Generated by Django 4.2.2 on 2023-07-31 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0015_coin_remove_cryptowalletaddress_currency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CryptoWalletAddress',
            new_name='CoinAddress',
        ),
    ]
