# Generated by Django 4.2.2 on 2023-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0016_rename_cryptowalletaddress_coinaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayprofit',
            options={'ordering': ['-date_created'], 'verbose_name': 'Bot day profit'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-rate'], 'verbose_name': 'Coin exchange rate'},
        ),
        migrations.AlterModelOptions(
            name='profittransaction',
            options={'verbose_name': 'User profit transaction'},
        ),
        migrations.AlterModelOptions(
            name='profitwallet',
            options={'verbose_name': 'User profit'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date_created'], 'verbose_name': 'Balance transaction'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'User wallet'},
        ),
        migrations.AlterModelOptions(
            name='walletreplenishmentrequest',
            options={'verbose_name': 'Balance replenishment'},
        ),
        migrations.AlterModelOptions(
            name='walletwithdrawalrequest',
            options={'verbose_name': 'Balance withdrawal'},
        ),
        migrations.AddField(
            model_name='coin',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
