# Generated by Django 4.2.2 on 2023-08-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0017_alter_dayprofit_options_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('owners_balance', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('owners_profit', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('users_profit', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('profit_relative',
                 models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='relative profit %')),
                ('percentage_contribution',
                 models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='owners deposit %')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_replenishment', models.DateTimeField(blank=True, null=True)),
                ('last_withdrawal', models.DateTimeField(blank=True, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.coin')),
            ],
            options={
                'verbose_name': 'Overall Info',
            },
        ),
    ]
