# Generated by Django 4.2.2 on 2023-08-02 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0020_alter_wallet_percentage_of_total_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfitTransaction',
        ),
    ]
