# Generated by Django 4.2.2 on 2023-08-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0021_delete_profittransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profitwallet',
            old_name='balance',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='profitwallet',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
