# Generated by Django 4.2.2 on 2023-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0022_rename_balance_profitwallet_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='percentage_of_total_balance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True,
                                      verbose_name='Percentage of total balance'),
        ),
    ]
