# Generated by Django 4.2.2 on 2023-08-03 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0025_alter_wallet_percentage_of_total_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalwallet',
            old_name='total_with_profit',
            new_name='total_balance_with_profit',
        ),
    ]
