# Generated by Django 4.2.2 on 2023-08-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0026_rename_total_with_profit_totalwallet_total_balance_with_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.coin')),
            ],
            options={
                'verbose_name': 'Coin Network',
                'ordering': ['coin'],
            },
        ),
    ]
