# Generated by Django 4.2.2 on 2023-08-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0028_usercoinaddress_delete_coinaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerCoinAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.coin')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.coinnetwork')),
            ],
        ),
    ]
