# Generated by Django 4.2.2 on 2023-08-08 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0029_ownercoinaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.coinnetwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletreplenishmentrequest',
            name='network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.coinnetwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletwithdrawalrequest',
            name='network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.coinnetwork'),
            preserve_default=False,
        ),
    ]
