# Generated by Django 4.2.2 on 2023-08-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0030_transaction_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='walletreplenishmentrequest',
            name='txid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='walletwithdrawalrequest',
            name='txid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
